import type { Env } from "@rephoto/contracts";
import { createFaceEngine, type FaceEngine } from "@rephoto/face-engine";

export function loadFaceEngine(env: Env): FaceEngine {
  return createFaceEngine({
    ...process.env,
    FACE_ENGINE: env.FACE_ENGINE,
    DATABASE_URL: env.DATABASE_URL,
    AWS_REGION: env.AWS_REGION,
    REKOGNITION_COLLECTION_PREFIX: env.REKOGNITION_COLLECTION_PREFIX,
    REKOGNITION_SEARCH_MAX_FACES: String(env.REKOGNITION_SEARCH_MAX_FACES),
    REKOGNITION_INDEX_TPS: String(env.REKOGNITION_INDEX_TPS),
    REKOGNITION_SEARCH_TPS: String(env.REKOGNITION_SEARCH_TPS),
    FACE_SERVICE_URL: env.FACE_SERVICE_URL,
    INSIGHTFACE_MIN_COSINE: String(env.INSIGHTFACE_MIN_COSINE),
    INSIGHTFACE_SURE_COSINE: String(env.INSIGHTFACE_SURE_COSINE),
    INSIGHTFACE_MAX_FACES: String(env.INSIGHTFACE_MAX_FACES),
    INSIGHTFACE_MIN_FACE_QUALITY: String(env.INSIGHTFACE_MIN_FACE_QUALITY),
    FACE_INDEX_TPS: String(env.FACE_INDEX_TPS),
    FACE_SEARCH_TPS: String(env.FACE_SEARCH_TPS),
  });
}
